#服务器的端口号
server:
  port: 8080
#数据连接的配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/csuft-tk-project?chartsetEncoding=utf-8&&serverTimezone=UTC&&useUnicode=true
    username: root
    password: root
#mybatis
mybatis:
  mapper-locations: classpath:com/csuft/mapper/*Mapper.xml
  #实体类别名
  type-aliases-package: com.csuft.entity
